import Albicy from '../img/Albicy_240x240.jpg';
import Voronov from '../img/Voron_240x240.jpg';
import Ponkrashov from '../img/Ponkr_240x240.jpg';
import Renfro from '../img/Renf_240x240.jpg';
import Khvorostov from '../img/Khvo_240x240.jpg';
import Hollinz from '../img/Holli_240x240.jpg';
import Abromajtiz from '../img/Abro_240x240.jpg';
import Zubkov from '../img/Zub_240x240.jpg';
import Ponitka from '../img/Poni_240x240.jpg';
import Thomas from '../img/Tom_240x240.jpg';
import Trushkin from '../img/Tru_240x240.jpg';
import Iverson from '../img/Iver_240x240.jpg';
import Ayon from '../img/Ayon_240x240.jpg';
import Pushkov from '../img/Pukh_240x240.jpg';

const ROLES = {
  CENTER: 'Центровой',
  FORWARD: 'Форвард',
  GUARD: 'Защитник',
};

const players = [
  {
    id: 1,
    name: 'Эндрю Альбиси',
    number: 6,
    role: ROLES.GUARD,
    age: 29,
    height: 178,
    weight: 77,
    country: 'Франция',
    photo: Albicy,
    images: [],
  },
  {
    id: 2,
    name: 'Евгений Воронов',
    number: 18,
    role: ROLES.GUARD,
    age: 33,
    height: 194,
    weight: 95,
    country: 'Россия',
    photo: Voronov,
    images: [],
  },
  {
    id: 3,
    name: 'Антон Понкрашов',
    number: 7,
    role: ROLES.GUARD,
    age: 33,
    height: 200,
    weight: 93,
    country: 'Россия',
    photo: Ponkrashov,
    images: [],
  },
  {
    id: 4,
    name: 'Алекс Ренфро',
    number: 12,
    role: ROLES.GUARD,
    age: 33,
    height: 191,
    weight: 80,
    country: 'США',
    photo: Renfro,
    images: [],
  },
  {
    id: 5,
    name: 'Дмитрий Хвостов',
    number: 13,
    role: ROLES.GUARD,
    age: 30,
    height: 190,
    weight: 84,
    country: 'Россия',
    photo: Khvorostov,
    images: [],
  },
  {
    id: 6,
    name: 'Остин Холлинз',
    number: 9,
    role: ROLES.GUARD,
    age: 27,
    height: 193,
    weight: 86,
    country: 'США',
    photo: Hollinz,
    images: [],
  },
  {
    id: 7,
    name: 'Тим Абромайтис',
    number: 21,
    role: ROLES.GUARD,
    age: 30,
    height: 203,
    weight: 107,
    country: 'США',
    photo: Abromajtiz,
    images: [],
  },
  {
    id: 8,
    name: 'Андрей Зубков',
    number: 20,
    role: ROLES.GUARD,
    age: 28,
    height: 205,
    weight: 100,
    country: 'Россия',
    photo: Zubkov,
    images: [],
  },
  {
    id: 9,
    name: 'Матеуш Понитка',
    number: 25,
    role: ROLES.GUARD,
    age: 26,
    height: 198,
    weight: 95,
    country: 'Польша',
    photo: Ponitka,
    images: [],
  },
  {
    id: 10,
    name: 'Уилл Томас',
    number: 10,
    role: ROLES.GUARD,
    age: 33,
    height: 203,
    weight: 104,
    country: 'США',
    photo: Thomas,
    images: [],
  },
  {
    id: 11,
    name: 'Владислав Трушкин',
    number: 16,
    role: ROLES.GUARD,
    age: 26,
    height: 201,
    weight: 103,
    country: 'Россия',
    photo: Trushkin,
    images: [],
  },
  {
    id: 12,
    name: 'Колтон Айверсон',
    number: 4,
    role: ROLES.GUARD,
    age: 30,
    height: 213,
    weight: 116,
    country: 'США',
    photo: Iverson,
    images: [],
  },
  {
    id: 13,
    name: 'Густаво Айон',
    number: 34,
    role: ROLES.GUARD,
    age: 34,
    height: 208,
    weight: 113,
    country: 'Мексика',
    photo: Ayon,
    images: [],
  },
  {
    id: 14,
    name: 'Антон Пушков',
    number: 14,
    role: ROLES.GUARD,
    age: 30,
    height: 208,
    weight: 100,
    country: 'Россия',
    photo: Pushkov,
    images: [],
  },
];

export default players;
